jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug structure
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: Run Lint
        run: |
          cd backend
          flake8 .

      - name: Run Tests
        run: |
          cd backend
          pytest --cov=app --cov-report=term-missing

      - name: Security Scan
        run: |
          cd backend
          bandit -r app
